[project]
name = "collision-probability-estimation"
version = "0.1.0"
description = "Python package for analytic collision probability calculation of vehicle trajectories under state uncertainties"
license = "LGPL-3.0-or-later"
readme = "README.md"
authors = [
    { name = "Marc Kaufeld", email = "marc.kaufeld@tum.de" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.3",
    "scipy>=1.17.1",
    "shapely>=2.1.2",
]

[project.optional-dependencies]
use_torch = [
    "torch>=2.10.0",
]
plot = [
    "matplotlib>=3.10.8",
]

[project.scripts]
state_coll_prob = "script_collision_state:main"
traj_coll_prob = "script_collision_trajectory:main"

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"
